/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpanishRouteImport } from './routes/spanish'
import { Route as SamsungRouteImport } from './routes/samsung'
import { Route as RussianRouteImport } from './routes/russian'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as GooglePixelRouteImport } from './routes/google-pixel'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SpanishRoute = SpanishRouteImport.update({
  id: '/spanish',
  path: '/spanish',
  getParentRoute: () => rootRouteImport,
} as any)
const SamsungRoute = SamsungRouteImport.update({
  id: '/samsung',
  path: '/samsung',
  getParentRoute: () => rootRouteImport,
} as any)
const RussianRoute = RussianRouteImport.update({
  id: '/russian',
  path: '/russian',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePixelRoute = GooglePixelRouteImport.update({
  id: '/google-pixel',
  path: '/google-pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/english': typeof EnglishRoute
  '/google-pixel': typeof GooglePixelRoute
  '/iphone': typeof IphoneRoute
  '/login': typeof LoginRoute
  '/russian': typeof RussianRoute
  '/samsung': typeof SamsungRoute
  '/spanish': typeof SpanishRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/english': typeof EnglishRoute
  '/google-pixel': typeof GooglePixelRoute
  '/iphone': typeof IphoneRoute
  '/login': typeof LoginRoute
  '/russian': typeof RussianRoute
  '/samsung': typeof SamsungRoute
  '/spanish': typeof SpanishRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/english': typeof EnglishRoute
  '/google-pixel': typeof GooglePixelRoute
  '/iphone': typeof IphoneRoute
  '/login': typeof LoginRoute
  '/russian': typeof RussianRoute
  '/samsung': typeof SamsungRoute
  '/spanish': typeof SpanishRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/english'
    | '/google-pixel'
    | '/iphone'
    | '/login'
    | '/russian'
    | '/samsung'
    | '/spanish'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/english'
    | '/google-pixel'
    | '/iphone'
    | '/login'
    | '/russian'
    | '/samsung'
    | '/spanish'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/english'
    | '/google-pixel'
    | '/iphone'
    | '/login'
    | '/russian'
    | '/samsung'
    | '/spanish'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EnglishRoute: typeof EnglishRoute
  GooglePixelRoute: typeof GooglePixelRoute
  IphoneRoute: typeof IphoneRoute
  LoginRoute: typeof LoginRoute
  RussianRoute: typeof RussianRoute
  SamsungRoute: typeof SamsungRoute
  SpanishRoute: typeof SpanishRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spanish': {
      id: '/spanish'
      path: '/spanish'
      fullPath: '/spanish'
      preLoaderRoute: typeof SpanishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samsung': {
      id: '/samsung'
      path: '/samsung'
      fullPath: '/samsung'
      preLoaderRoute: typeof SamsungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/russian': {
      id: '/russian'
      path: '/russian'
      fullPath: '/russian'
      preLoaderRoute: typeof RussianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-pixel': {
      id: '/google-pixel'
      path: '/google-pixel'
      fullPath: '/google-pixel'
      preLoaderRoute: typeof GooglePixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EnglishRoute: EnglishRoute,
  GooglePixelRoute: GooglePixelRoute,
  IphoneRoute: IphoneRoute,
  LoginRoute: LoginRoute,
  RussianRoute: RussianRoute,
  SamsungRoute: SamsungRoute,
  SpanishRoute: SpanishRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
